controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

#test_action:
 #   path: /test/test
  #  controller: App\Controller\testController::test
